### ISSUE TITLE
feature request (?): seeing through the eyes of an individual boid

### ISSUE THREAD

**Issue by saitogroup** [Corollarium/babylon-boids#2]
I guess I'm going to try to work on it, but I don't know if I'll be successful.

**Comment by brunobg** [comment]
I don't have any use for it, but I think all you have to do is use a FollowCamera 
https://doc.babylonjs.com/api/classes/babylon.followcamera or something like this https://forum.babylonjs.com/t/how-to-properly-attach-the-camara-to-an-object/2102.

If you do implement send a PR and I'll accept it.
