### ISSUE TITLE
using add force

### ISSUE THREAD

**Issue by saitogroup** [Corollarium/babylon-boids#5]
addForce(c)
Adds a force callback function. This enables you to change the simulation with your own forces. Called fr

callback c A valid JS function, called on update() for each boid. Receives as parameters: (BoidsManager, Boid)

//

do you have an example of this being used somewhere? Or would you be open to showing me an example of how your would use it? I'm using this for this project: https://www.instagram.com/p/CIxSG1BFR1Z/ VR boids under your control

**Comment by brunobg** [comment]
Sorry, I forgot to answer this!

Your callback simply has to return a vector3 in the force direction and with the corresponding correct length. This will be added to the rest of the simulation. You can look at the `_force*` methods for examples. 

Let me know if you have any other questions!

**Comment by saitogroup** [comment]
Ah, I get it now! What about the "power" of relative forces vis-a-vis each other. e.g. if I add a force that tells the boids to come to the player, is there a standard way in this library to make that force more powerful than the other forces of alignment, cohesion, etc.

**Comment by brunobg** [comment]
This is a very simple physics simulator, so all forces are added and the resulting vector is applied for the frame time. So the larger the magnitude of the vector, the larger the force applied. Check a basic Newtonian physics tutorial if you need extra information about it.
